spring:
  application:
    name: keyun-autocode-backend
  profiles:
    active: local # 激活环境，获取秘钥key
  data:
    redis:
      database: 0
      host: ${redis.host}
      port: ${redis.port}
      ttl: 3600 # 记忆过期时间
      username: ${redis.username:} # 如果没有用户名，留空
      password: ${redis.password:} # 如果没有密码，留空
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.host}:${datasource.port}/keyun_autocode?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${datasource.username}
    password: ${datasource.password}
# AI
langchain4j:
  open-ai:
    # deepseek
    chat-model:
      base-url: https://api.deepseek.com/v1
      api-key: ${DEEPSEEK_API_KEY}
      model-name: deepseek-chat
      #生产环境关闭日志
      log-requests: ${ai.reqLog:true}
      log-responses: ${ai.respLog:true}
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
      max-retries: 3
    dashscope:
      base-url: ${dashscope.base-url}
      api-key: ${dashscope.api-key}
      model-name: ${dashscope.model-name}
      log-requests: ${ai.reqLog:true}
      log-responses: ${ai.respLog:true}

#响应给前端app部署地址（本地：http://localhost:8123 ，远程：http://{ip或域名}/dish）：
app:
  deploy:
    host: ${server.host}

server:
  port: 8123
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: now()
      logic-not-delete-value: 'null'
# 日志配置
logging:
  level:
    # 替换为你的 mapper 接口所在的包路径
    com.jstart.keyunautocodebackend.mapper: debug  # 输出该包下的 SQL 日志
    # 可选：MyBatis 核心日志（如需更详细的信息）
    #com.baomidou.mybatisplus: info

# Sa-Token: https://sa-token.cc
sa-token:
  token-name: keeToken
  timeout: 2592000
  token-style: uuid
  is-log: true

# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: ${cos.host}
    secretId: ${cos.secretId}
    secretKey: ${cos.secretKey}
    region: ${cos.region}
    bucket: ${cos.bucket}

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jstart.keyunautocodebackend.controller
# knife4j
knife4j:
  basic:
    enable: ${knife4j.enable:false}
    #线上环境要改成正式账号密码，否则谁都能访问
    username: ${knife4j.username:root}
    password: ${knife4j.password:123456}
  enable: true
  setting:
    language: zh_cn

